//
//  CameraViewController.swift
//  SelfieBet
//
//  Created by 용태권 on 2020/07/07.
//  Copyright © 2020 Yongtae.Kwon. All rights reserved.
//

import AVFoundation
import UIKit

class CameraViewController: UIViewController {
    let cameraController = CameraController()
 
    @IBOutlet weak var captureButton: UIButton?
 
    ///Displays a preview of the video output generated by the device's cameras.
    @IBOutlet weak var capturePreviewView: UIView?
 
//    ///Allows the user to put the camera in photo mode.
//    @IBOutlet fileprivate var toggleCameraButton: UIButton!
//    @IBOutlet fileprivate var toggleFlashButton: UIButton!
 
    override var prefersStatusBarHidden: Bool { return true }
}
 
extension CameraViewController {
    override func viewDidLoad() {
        func configureCameraController() {
            cameraController.prepare {(error) in
                if let error = error {
                    print(error)
                }
                guard let capturePreviewView = self.capturePreviewView else { return }
                try? self.cameraController.displayPreview(on: capturePreviewView)
            }
        }
 
        func styleCaptureButton() {
            guard let captureButton = self.captureButton else { return }
            captureButton.layer.borderColor = UIColor.black.cgColor
            captureButton.layer.borderWidth = 2

            captureButton.layer.cornerRadius = min(captureButton.frame.width, captureButton.frame.height) / 2
        }

        styleCaptureButton()
        configureCameraController()
    }
}
